version: "3"
services:
  mysql:
    # 指定启动后的容器名
    container_name: mysql
    # 指定镜像
    image: mysql:8
    # 指定端口映射
    ports:
      - "3301:3306"
    # 指定数据卷
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/logs:/var/log/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    # 指定环境变量
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password

  imageshare:
    # 指定启动后的容器名
    container_name: imageshare
    image: "${IMAGE}:${VERSION}"
    ports:
      - "8088:8088"
    depends_on:
      - mysql
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
